### ISSUE TITLE
Basic Instructions Failure

### ISSUE THREAD

**Issue by antofthy** [phicau/olaFlow#1]
basic instructions are...

```
git clone git://github.com/phicau/olaFlow.git
cd olaFlow/
./allMake 
```

But this just errors...

```
./allMake: line 3: [: ==: unary operator expected
./allMake: line 69: wclean: command not found
./allMake: line 71: wmake: command not found
\n\nOlaFlow project wave generation boundary conditions compilation failed
```

This does not inspire great confidence in the code when basic BASH scripting fails!

**Comment by phicau** [comment]
The user needs to have OpenFOAM installed and loaded before compiling olaFlow.
Posting with such a prepotency does not inspire great confidence in the user!

**Comment by FokkeDijkstra** [comment]
I ran into the same issue. Some basic sanity checking would have been appropriate. Furthermore the instructions don't even mention that OpenFOAM needs to be loaded.

**Comment by phicau** [comment]
Thanks for your feedback Fokke. Please note the following paragraph in the description of olaFlow:

> This free and open source project is committed to bringing the latest advances in the simulation of wave dynamics to the OpenFOAM® and FOAM-extend communities.

I will add a small note in the compilation instructions to make sure it is crystal clear.
